### PR TITLE
Add settings

### PR DESCRIPTION
**Pull request by shomykohai**
## Summary

Adds settings:
* Quest pools override
* Require objective_completed
* Additional pools paths

## Checklist

- [x] This PR changes something in the code (e.g. for better performance).
    - [x] If any code changes had taken place, I've tested them before committing.
- [x] This PR adds something new.
- [ ] This PR fixes an issue. 
- [ ] This PR includes breaking changes.
- [ ] This PR is not code related (e.g. README, Documentation)

### CODE REVIEW

**Comment by dnbroo** [comment]
Hey shomy!

Just started up my project and installed your update. 

looks like im getting this:
"Invalid type in GDScript utility function "load()". Cannot convert argument 1 from Nil to String."

in quest_manager.gd:
```
func _init() -> void:  
        # Ovverride default pools if specified in project settings.  
        if available.get_script().resource_path != QuestSystemSettings.get_config_setting("use_available_pool"): <-----------  
                var pool := load(QuestSystemSettings.get_config_setting("use_available_pool"))
```

I tried adding a bool under Quest System config for "use_avilable_pool" and it still didn't seem to like it. When looking I also didn't see a QuestSystemSettings.gd, so i'm not sure if we are supposed to have that. I haven't worked too much with custom settings so I may not know how it works.

Thanks again for the awesome quest system :)

**Comment by shomykohai** [comment]
> Hey shomy!
> 
> Just started up my project and installed your update. 
> 
> looks like im getting this:
> "Invalid type in GDScript utility function "load()". Cannot convert argument 1 from Nil to String."
> 
> in quest_manager.gd:
> ```
> func _init() -> void:  
>         # Ovverride default pools if specified in project settings.  
>         if available.get_script().resource_path != QuestSystemSettings.get_config_setting("use_available_pool"): <-----------  
>                 var pool := load(QuestSystemSettings.get_config_setting("use_available_pool"))
> ```
> 
> I tried adding a bool under Quest System config for "use_avilable_pool" and it still didn't seem to like it. When looking I also didn't see a QuestSystemSettings.gd, so i'm not sure if we are supposed to have that. I haven't worked too much with custom settings so I may not know how it works.
> 
> Thanks again for the awesome quest system :)

Mmh I think I messed up something with the settings 😅, I suggest you using 1.2.0 while I fix this. There's no much difference between the two versions apart for the settings so you should be OK!
I'll try to fix this today when I have time.

**Comment by dnbroo** [comment]
Sounds good with me 😎 

It happens after Godot has already opened and I'm starting up my game!

**Comment by shomykohai** [comment]
> Sounds good with me 😎 
> 
> It happens after Godot has already opened and I'm starting up my game!

Have you tried reloading the project first?

**Comment by dnbroo** [comment]
Yep, I tried a few things.

Troubleshooting taken:
- reloaded project
- Deleted questsystem  autoload, reloaded project
- Enabled questsystem Autoload
- tried creating my own custom setting for 'use_available_pool'
- Deleted QuestSystem, Installed QuestSystem

It seems the last step worked because it kept your 1.2 version

**Comment by shomykohai** [comment]
> Yep, I tried a few things.
> 
> Troubleshooting taken:
> - reloaded project
> - Deleted questsystem  autoload, reloaded project
> - Enabled questsystem Autoload
> - tried creating my own custom setting for 'use_available_pool'
> - Deleted QuestSystem, Installed QuestSystem
> 
> It seems the last step worked because it re-installed your 1.2 version

I see.
I'll try to replicate the issue and see what could be the cause. Right now what I'm thinking of is that I forgot to initialize the settings after the auto-updater before the auto updater reloads the plugin.

**Comment by shomykohai** [comment]
> Yep, I tried a few things.
> 
> Troubleshooting taken:
> 
> * reloaded project
> * Deleted questsystem  autoload, reloaded project
> * Enabled questsystem Autoload
> * tried creating my own custom setting for 'use_available_pool'
> * Deleted QuestSystem add-on folder, re-installed QuestSystem add-on folder
> 
> It seems the last step worked because it re-installed your 1.2 version

Tried to fix it. Could you tell me if you have the same issue with the latest commit on the main branch?

**Comment by dnbroo** [comment]
Yep that fixed it! My project launched as expected!

You rock! 🔥😎

**Comment by shomykohai** [comment]
> Yep that fixed it! My project launched as expected!
> 
> You rock! 🔥😎

Perfect, I'll push the update now!

**Pull request merged**
